### ISSUE TITLE
leptonica v1.83.0

### ISSUE THREAD

**Issue by ava57r** [ccouzens/leptonica-plumbing#5]
Hello.
It does not work on new leptonica version v1.83.0

I tried to compile my project.
I got an error

```log
error[E0609]: no field `n` on type `&box::leptonica_sys::Boxa`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/leptonica-plumbing-0.6.0/src/boxa.rs:50:18
   |
50 |         if lboxa.n <= std::convert::TryFrom::try_from(i).ok()? {
   |                  ^ unknown field
   |
   = note: available fields are: `_address`

error[E0609]: no field `box_` on type `&box::leptonica_sys::Boxa`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/leptonica-plumbing-0.6.0/src/boxa.rs:53:59
   |
53 |             unsafe { Some(crate::BorrowedBox::new(&*lboxa.box_.offset(i))) }
   |                                                           ^^^^ unknown field
   |
   = note: available fields are: `_address`

error[E0609]: no field `n` on type `&box::leptonica_sys::Pixa`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/leptonica-plumbing-0.6.0/src/pixa.rs:49:18
   |
49 |         if lpixa.n <= std::convert::TryFrom::try_from(i).ok()? {
   |                  ^ unknown field
   |
   = note: available fields are: `_address`

error[E0609]: no field `pix` on type `&box::leptonica_sys::Pixa`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/leptonica-plumbing-0.6.0/src/pixa.rs:52:58
   |
52 |             unsafe { Some(crate::BorrowedPix::new(*lpixa.pix.offset(i))) }
   |                                                          ^^^ unknown field
   |
   = note: available fields are: `_address`

```

**Comment by ccouzens** [comment]
How strange

The fields still seem to be there

https://github.com/DanBloomberg/leptonica/blob/master/src/pix_internal.h#L234
https://github.com/DanBloomberg/leptonica/blob/master/src/pix_internal.h#L267

What operating system are you using and how did you install leptonica? I might be able to replicate your setup.

**Comment by ava57r** [comment]
I found in release notes https://github.com/DanBloomberg/leptonica/blob/master/version-notes.html#L116

I install from source code

**Comment by ava57r** [comment]
rename .so lib https://github.com/DanBloomberg/leptonica/commit/29a33a364848f67d0fc102fda6d4ed858d7470b3

**Comment by ava57r** [comment]
split interface https://github.com/DanBloomberg/leptonica/commit/e8b670d9357c78a6a93fa23e27bb25675c695fa3

**Comment by ava57r** [comment]
tesseract has prepared https://github.com/tesseract-ocr/tesseract/pull/3851

**Comment by ccouzens** [comment]
I've managed to replicate the issue

**Comment by ccouzens** [comment]
Just to keep you updated:

I'm working on this. It requires refactoring and a new interface as some things we could do previously are no longer possible.

I'm mostly there with this repository, but I want to get branches of tesseract-plumbing, LepTess and tesseract-rs using it too to ensure the new interface is good.

I also want to improve the test coverage.

**Comment by PureSci** [comment]
Hello! I am also facing the issue. What can be a possible temp solution to this? Like downgrading leptonica or...

**Comment by ccouzens** [comment]
> Hello! I am also facing the issue. What can be a possible temp solution to this? Like downgrading leptonica or...

Hi @PureSci ,

Sorry to hear you're also having the issue. Yes, in the mean time can you downgrade leptonica.

I've been building it manually so I can use 1.83.0 to work with the new ABI. You'll need to go back to 1.82.0 or earlier.

These are my notes on building it manually.

```
# fedora
sudo dnf builddep leptonica-devel
# ubuntu
sudo apt-get build-dep libleptonica-dev

./autogen.sh

# prefix assumes you don't want to install it system wide
./configure "--prefix=$(pwd)/local"
make
make install
```

Assuming you used a `--prefix` you'll need to set `LD_LIBRARY_PATH` and `PKG_CONFIG_PATH` (eg `LD_LIBRARY_PATH=/var/home/chris/Documents/github.com/DanBloomberg/leptonica/local/lib PKG_CONFIG_PATH=/var/home/chris/Documents/github.com/DanBloomberg/leptonica/local/lib/pkgconfig`  when compiling or running code that uses it (PKG_CONFIG_PATH is only used for compiling).

**Comment by ccouzens** [comment]
I've raised a PR here https://github.com/ccouzens/leptonica-plumbing/pull/6.

Please feel free to review and comment.

**Comment by dbernatt** [comment]
How to downgrade into 1.82.0 if I installed on Windows 10?

Install command on windows: `vcpkg install leptonica:x64-windows-static-md`

**Comment by ccouzens** [comment]
@dbernatt I don't know.

I tried to use `vcpkg` to go the other way (get 1.83.0) when I was first starting to work on this issue. I struggled with specifying the version at the time.

When Googling I found some information about checking out an older version of `vcpkg` and having that give older versions of packages.

As a work around you might be able to wait until the fix is merged.
Or you could specify the git branch in your cargo.toml

```
leptonica-plumbing = { git = "https://github.com/ccouzens/leptonica-plumbing", branch = "leptonica_1.83.0" }
```

**Comment by MGSousa** [comment]
@dbernatt You can use the vcpkg.json manifest for overriding leptonica version or other packages (as a workaround for now).
```json
{
  "dependencies": [
    "leptonica",
    "tesseract",
    "vcpkg-cmake-config",
    "vcpkg-cmake-get-vars",
    "vcpkg-cmake",
  ],
  "overrides": [
    {
      "name": "leptonica",
      "version": "1.82.0"
    }
  ]
}
```
Then just `vcpkg x-update-baseline --add-initial-baseline` and `vcpkg install --triplet=x64-windows-static-md`

**Comment by eniolajayi** [comment]
@MGSousa Tried what you suggested and still did not fix the issue. @ccouzens Any updates on a fix for this?

**Comment by ccouzens** [comment]
> @ccouzens Any updates on a fix for this?

@eniolajayi yes. I've released leptonica-plumbing 1.0.0 which fixes this.

But I suspect you're not using this directly. I've been waiting until some upstream projects are fixed before making an announcement.

Tesseract-plumbing uses this updated version in 0.8.0.

LepTess has an open pr on it. If there's no comments soon I'll merge and release. https://github.com/houqp/leptess/pull/54

**Comment by ccouzens** [comment]
Hey all,

Everything is merged and released.
If you're on leptonica-plumbing:1.0.0

Or the upstream projects
tesseract-plumbing:0.8.0
leptess:0.14.0
tesseract:0.12.1

Then everything should just work with leptonica-1.83.0.

Let me know if otherwise.

**Comment by eniolajayi** [comment]
@ccouzens it's fixed! Thanks
